name: Go

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        check-latest: true

    - name: Verify dependencies
      run: |
        go mod download
        go mod verify

    - name: Build
      run: go build -v .

    - name: Run basic tests
      run: |
        # Test that the binary can be built and runs without errors
        go build -o favmaster .
        ./favmaster --help || true

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        check-latest: true

    - name: Build Linux AMD64
      run: GOOS=linux GOARCH=amd64 go build -o favmaster-linux-amd64 .

    - name: Build Linux ARM64
      run: GOOS=linux GOARCH=arm64 go build -o favmaster-linux-arm64 .

    - name: Build Windows AMD64
      run: GOOS=windows GOARCH=amd64 go build -o favmaster-windows-amd64.exe .

    - name: Build Darwin AMD64
      run: GOOS=darwin GOARCH=amd64 go build -o favmaster-darwin-amd64 .

    - name: Build Darwin ARM64
      run: GOOS=darwin GOARCH=arm64 go build -o favmaster-darwin-arm64 .

    - name: Show build artifacts
      run: ls -la favmaster-*

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          favmaster-linux-amd64
          favmaster-linux-arm64
          favmaster-windows-amd64.exe
          favmaster-darwin-amd64
          favmaster-darwin-arm64
        generate_release_notes: true

  install-test:
    name: Install Test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        check-latest: true

    - name: Test go install
      run: |
        # Test that the module can be installed via go install
        go install .
        ${GOPATH}/bin/favmaster --help || true
